name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom-staging[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: A new test
      id: a-new-test
      uses: education/autograding-command-grader@v1
      with:
        test-name: A new test
        setup-command: sudo -H pip3 install pytest
        command: pytest
        timeout: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        A-NEW-TEST_RESULTS: "${{steps.a-new-test.outputs.result}}"
      with:
        runners: a-new-test
